spring:
 datasource:
  url: jdbc:mysql://localhost:3306/JAVA17_SPRING
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password:
 jpa:
  hibernate:
      ddl-auto: update
 jackson:
  time-zone: Asia/Tehran
  date-format: yyyy-MM-dd'T'HH:mm:ss
 data:
  mongodb:
   uri: mongodb://localhost:27017/java17
#shaparak:
#  url: https://shaparak.ir
dev: true
server:
 port: 8081
