spring:
 datasource:
  url: jdbc:mysql://localhost:3306/JAVA17_SPRING
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password:
 jpa:
  hibernate:
      ddl-auto: update
#shaparak:
#  url: https://shaparak.ir
dev: true